### ISSUE TITLE
stable branch

### ISSUE THREAD

**Issue by emorrp1** [flathub/net.veloren.veloren#14] opened 2021-03-29 00:26 UTC
Last week [v0.9.0 released](https://veloren.net/devblog-112/), but installing it now *claims* to be v0.8, yet the commit hash provided is actually only a day old.

```
:~ $ flatpak list --app
Name    Application ID          Version         Branch  Origin  Installation
Veloren net.veloren.veloren     0.8.0-c8c086d   stable  flathub user
```

So please a) downgrade the "stable" branch to official v0.9.0, b) publish 0.9.0-c8c086d to flathub-beta

**Comment by tim77** [comment] 2021-03-29 17:12
This discussed earlier. No point to have tagged version of Veloren in Stable Flathub branch since multiplayer will not work almost on the same day after release.

**Comment by emorrp1** [comment] 2021-03-29 18:51
I see you've fixed the claimed version.

I've found [your previous discussion](https://github.com/flathub/net.veloren.veloren/issues/1#issuecomment-619005189), but you've also said that [will happen from time to time](https://github.com/flathub/net.veloren.veloren/issues/6#issuecomment-717766181) anyway, so even going by latest commits the flatpak still falls behind compatibility with the one official main server. Given how trivial flatpak/veloren makes it to spin up a local server `flatpak run --command=veloren-server-cli net.veloren.veloren` it would be nice if two people installing the flatpak version could actually play together without also having to synchronise when they happen to run `flatpak update`.

I know it's "just alpha", but given the additional hype each tagged release notes generates, I hope that soon the demand (like this issue) for a stable client version will grow. Once the beta channel has been published, then the instructions can be updated to show how to use it in place of Airshipper for `server.veloren.net` multiplayer. Please reconsider, and even if you still object to a stable branch for now, perhaps revisit it after each release? (I'm assuming that you have a more direct connection with the Veloren community).

**Comment by tim77** [comment] 2021-03-29 19:03
> Given how trivial flatpak/veloren makes it to spin up a local server flatpak run --command=veloren-server-cli net.veloren.veloren it would be nice if two people installing the flatpak version could actually play together without also having to synchronise when they happen to run flatpak update.

I totally agree, this would be awesome. I have no clear numbers, but player base is still low and just trying to satisfy majority here. `flathub-beta` branch is hard to discover. Even if document it in official wiki. This split even more player base with different Veloren versions/builds and confuse them.

But i am not against at all. But i think this requires more wider discussion. Also need to ping and ask @zesterer.

**Comment by emorrp1** [comment] 2021-03-29 19:28
Thank you for understanding, I'm not on Discord (unless there's a matrix bridge?), so I'll just put a few more words here for the devs to consider.

I'd ask if someone went to install "Veloren" and got given v0.9.0, would they be able to enjoy the game such as it is? Would they be excited to share that experience, keep an eye out for new v0.10.0 features that make them want to upgrade; or would it be too buggy to recommend to friends and missing basic functionality expected of "Veloren"? Basically, it's just the same as rolling vs LTS distros, so at the moment you're only catering to rolling gamers (a limitation you might well decide you want to keep for now).

I can see the one official server compatibility being a critical factor, so would you be willing to create a `legacy.veloren.net` for tagged release users, or bless someone else's installation of v0.9.0? Even then, the ability to host your own instance is clearly part of Veloren's design, so you could even give it a different button "Local Multiplayer" with the "Online Multiplayer" pointing the user to information about the nightlies/beta channel.

**Comment by zesterer** [comment] 2021-03-29 19:38
To be honest, I'm not sure that shipping Veloren without Airshipper makes sense at this stage. The Flatpak build has confused a lot of people due to server incompatibility. Does Airshipper (i.e: downloading and executing binaries) fall within the permission system that flatpak provides?

**Comment by tim77** [comment] 2021-03-30 09:24
@zesterer 
> The Flatpak build has confused a lot of people due to server incompatibility. 

Not working at all Veloren binary shipped with Airshipper confused people even more. This is not something unusual and people complain that binary not work for them on their X-distro but flatpak version works fine.

As for server incompatibility - this could easily solved if upstream Veloren will push commits scheduled from staging to master branch for example and synced with updates on flathub. Lets say every two days at UTC±0:00. Now we have even bot which automatically sync rust-nightly toolchain with upstream Veloren toolchain.

> Does Airshipper (i.e: downloading and executing binaries) fall within the permission system that flatpak provides?

Flathub policy not against if upstream prefer to ship binaries. Basically proprietary binaries which no one can reproduce and which no guaranty to work. I personally not interesting in maintain such build, sorry. But this is not a problem and @gasinvein for example already packaged Airshipper for long time ago. Can't find right now this manifest.

Why Airshipper even needed for non Windows/macOS? There already best tool in regard to cross-distro, reproducibility, safely and reliability - it's called flatpak. When you offering for your users Airshipper you not offering them better UX.

@emorrp1 
> or would it be too buggy to recommend to friends and missing basic functionality expected of "Veloren"? Basically, it's just the same as rolling vs LTS distros, so at the moment you're only catering to rolling gamers (a limitation you might well decide you want to keep for now).

No, it's not the same in case with Veloren. The most bug-free version is a latest dev version. Also you can always rollback to any previous build with you friend and stick with this version (thanks flatpak). No limitation in this regard as you said. Rolling distros doesn't allow you to stick with specific version/build. But this is not the case of flatpak.

The most important point for such kind of game is still the same - MMOG where the player base and online has the meaning.

**Comment by zesterer** [comment] 2021-03-30 11:05
> As for server incompatibility - this could easily solved if upstream Veloren will push commits scheduled from staging to master branch for example and synced with updates on flathub. Lets say every two days at UTC±0:00. Now we have even bot which automatically sync rust-nightly toolchain with upstream Veloren toolchain.

@tim77 I think you're underestimating the rate of development. The public server frequently goes down multiple times per hour for updates. I don't think we've had a day where something hasn't been merged in weeks. The rate of updates is only climbing, too. We've discussed switching the server to a weekly release schedule, but there are quite a few problems associated with such a move that we're not yet in a position to deal with.

> Why Airshipper even needed for non Windows/macOS? There already best tool in regard to cross-distro, reproducibility, safely and reliability - it's called flatpak. When you offering for your users Airshipper you not offering them better UX.

Can flatpak handle an update rate of up to multiple builds per hour? I'm sceptical. If you think it can be done, then I'd like to hear how.

**Comment by emorrp1** [comment] 2021-03-30 11:34
> The public server frequently goes down multiple times per hour for updates.
> Can flatpak handle an update rate of up to multiple builds per hour?

Does Airshipper handle multiple updates per hour? Even assuming delta upgrades, that's a lot of downloading going on client-side.

> I think you're underestimating the rate of development. We've discussed switching the server to a weekly release schedule, but there are quite a few problems associated with such a move that we're not yet in a position to deal with.

@zesterer If that's the case then fair enough, Veloren isn't ready for a stable branch yet, but then why create tags? and I'll ask again: are players not able to enjoy the game as is, amongst themselves?

**Comment by zesterer** [comment] 2021-03-30 12:15
> Does Airshipper handle multiple updates per hour? Even assuming delta upgrades, that's a lot of downloading going on client-side.

Yes. We're working on delta updates. The update rate can vary (it's not uncommon to go 12 hours without an update during night time for EU/USA), but my point is that it *can often* be up to multiple per hour.

> Veloren isn't ready for a stable branch yet, but then why create tags?

Because it's important to create a timeline of the project's development and it provides an opportunity for us to tell players about new features.

> are players not able to enjoy the game as is, amongst themselves?

I'm not quite sure what you're asking here. An old build will work just fine on singleplayer or with a server also running the same build. However, Veloren's gameplay is generally enhanced within a multiplayer environment and I personally feel that it's a huge shame to miss out on that due to a client incompatibility.

**Comment by tim77** [comment] 2021-03-30 12:42
> Can flatpak handle an update rate of up to multiple builds per hour? I'm sceptical. If you think it can be done, then I'd like to hear how.

Flathub can. :) But flathub not CI. Probably i already abusing flathub by doing so often automatic builds of Veloren.

@zesterer we can have both - current build and we can package Airshipper on Flathub. Win-win. And all this document in Veloren wiki. Also you can create self-hosted flatpak repository for dev builds. For example GNOME doing this for dev apps https://wiki.gnome.org/Apps/Nightly.

**Comment by emorrp1** [comment] 2021-03-30 14:32
> > are players not able to enjoy the game as is, amongst themselves?
> 
> I'm not quite sure what you're asking here. An old build will work just fine on singleplayer or with a server also running the same build. However, Veloren's gameplay is generally enhanced within a multiplayer environment and I personally feel that it's a huge shame to miss out on that due to a client incompatibility.

@tim77 This all sounds quite positive actually, so I think with appropriate documentation follow-up (i.e. heavily recommending the dev version), a stable branch would be useful. If you agree, I'm happy to start work on some wording to put in a new wiki page?

**Comment by tim77** [comment] 2021-03-30 15:07
@emorrp1 the question is how to sync flathub builds with upstream Veloren is still open. Currently Veloren updating 5 times per week. Maybe we can raise this to every day build but even this could not enough for 100% compatibility with server build. @zesterer mentioned that they discussed switching the server to a weekly release schedule, but maybe once per two days would enough? This could solve almost entirely de-sync issues with client <-> server. Even if need an urgent hotfix - upstream could just press one button in GH Actions at any time and build new version.

Don't underestimate Flathub user base. Now we have almost 1000 downloads/updates for every new build and it keep growing. Also we have even few `aarch64` users. BTW people already asking for providing Veloren build for RPi. This flathub build and build in my COPR for CentOS/Fedora is the only one which i know to exist.

https://klausenbusk.github.io/flathub-stats/#ref=net.veloren.veloren&interval=infinity&downloadType=installs%2Bupdates.

**Comment by LunarEclipse363** [comment] 2021-04-26 16:07
For reference, we've now switched the main Veloren server to update once a day at 06:00 UTC.

We produce the builds for that with a scheduled CI pipeline, which is set up here: https://gitlab.com/veloren/veloren/-/pipeline_schedules?scope=active

**Comment by tim77** [comment] 2021-04-26 16:24
It seems like all build process in CI takes 1 hour 28 mins. We can try to guess the proper time for update checking on Flathub CI. But we also can automate entirely this procces and upstream Veloren CI when finished could trigger Flathub update.

Also i would like if we switch to daily updates on Flathub, but not sure since it takes decent resources primary in terms of disk space since flathub keep all builds and user can always rollback to any build/update at any time. Need to ask @barthalion can we use so many resources or maybe there are some alternative solutions possible.

**Comment by barthalion** [comment] 2021-05-07 09:55
Flathub build takes less than 30 minutes, and we are about to start pruning old builds regularily, so neither CI and disk space are an issue here.

**Closed as completed** 2021-05-17 10:33 UTC
